//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUILayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainGameForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainGameForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUILayer.MainGameForm", typeof(MainGameForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool battleLogLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("battleLogLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charALabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charALabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charALabel2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charALabel2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charBLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charBLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charBLabel2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charBLabel2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charCLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charCLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charCLabel2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charCLabel2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charDLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charDLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charDLabel2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charDLabel2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charELabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charELabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charELabel2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charELabel2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charFLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charFLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charFLabel2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charFLabel2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charGLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charGLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charGLabel2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charGLabel2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charHLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charHLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charHLabel2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charHLabel2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charILabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charILabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charILabel2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charILabel2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charJLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charJLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charJLabel2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charJLabel2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num10Label1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num10Label1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num10Label2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num10Label2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num1Label1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num1Label1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num1Label2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num1Label2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num2Label1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num2Label1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num2Label2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num2Label2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num3Label1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num3Label1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num3Label2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num3Label2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num4Label1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num4Label1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num4Label2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num4Label2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num5Label1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num5Label1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num5Label2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num5Label2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num6Label1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num6Label1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num6Label2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num6Label2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num7Label1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num7Label1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num7Label2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num7Label2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num8Label1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num8Label1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num8Label2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num8Label2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num9Label1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num9Label1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num9Label2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num9Label2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool opponentHitRatioLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("opponentHitRatioLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool opponentHitsLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("opponentHitsLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool opponentMissesLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("opponentMissesLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool opponentStatisticsGroupBox_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("opponentStatisticsGroupBox.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerFleetBox_Image {
            get {
                object obj = ResourceManager.GetObject("PlayerFleetBox.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool roundLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("roundLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TargetFleetBox_Image {
            get {
                object obj = ResourceManager.GetObject("TargetFleetBox.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool TargetLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("TargetLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool yourFleetLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("yourFleetLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool yourHitRatioLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("yourHitRatioLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool yourHitsLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("yourHitsLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool yourMissesLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("yourMissesLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool yourStatisticsGroupBox_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("yourStatisticsGroupBox.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
