//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUILayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlaceShips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlaceShips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUILayer.PlaceShips", typeof(PlaceShips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charALabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charALabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charBLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charBLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charCLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charCLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charDLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charDLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charELabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charELabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charFLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charFLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charGLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charGLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charHLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charHLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charILabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charILabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool charJLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("charJLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deckPictureBox_Image {
            get {
                object obj = ResourceManager.GetObject("deckPictureBox.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleteShip0Button_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("deleteShip0Button.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleteShip1Button_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("deleteShip1Button.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleteShip2Button_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("deleteShip2Button.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleteShip3Button_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("deleteShip3Button.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleteShip4Button_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("deleteShip4Button.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deployShip0Button_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("deployShip0Button.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deployShip1Button_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("deployShip1Button.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deployShip2Button_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("deployShip2Button.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deployShip3Button_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("deployShip3Button.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deployShip4Button_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("deployShip4Button.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap doneButton_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("doneButton.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool doneGroupBox_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("doneGroupBox.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num10Label_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num10Label.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num1Label_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num1Label.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num2label_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num2label.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num3Label_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num3Label.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num4Label_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num4Label.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num5Label_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num5Label.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num6Label_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num6Label.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num7Label_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num7Label.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num8Label_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num8Label.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool num9Label_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("num9Label.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool ship0GroupBox_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ship0GroupBox.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool ship1GroupBox_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ship1GroupBox.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool ship2GroupBox_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ship2GroupBox.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool ship3GroupBox_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ship3GroupBox.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool ship4GroupBox_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ship4GroupBox.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shipRotateButton_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("shipRotateButton.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool shipRotateGroupBox_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("shipRotateGroupBox.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
